### ISSUE TITLE
Make navigation tree for the APIs larger.

### ISSUE THREAD

**Issue by glennblock** [OpenBankProject/API-Explorer#1]
Having recently completed our app for the hackathon ,let me first say THANK YOU for the API Explorer. It was really helpful. As API architect for our project, I pretty much lived in the browser to figure things out.

One suggestion would be to add a navigation tree on the side that I can use to quickly navigate to a specific API. 

I used `ctrl+F` to navigate around, but a tree would help quickly to get an understanding of what APIs are present.

Building on top of that I'd suggest adding favorites. Allow users to basically favorite the common APIs they are using and store that in the backend. This way this information would flow to whatever device they are using.

**Comment by simonredfern** [comment]
Adding related comment from znurgl : A layout like this would be really helpful: https://getmondo.co.uk/docs/

**Comment by simonredfern** [comment]
API Explorer now has Left panel of API calls. Also support for filtering by Tags - but no UI elements yet. (note OBP API does make use of these tags in links)

**Comment by sebtesobe** [comment]
The left panel needs some improvement for high density displays. I suggest the following changed / added CSS rules:

``` css
.api-list {
  height: 100%;
}
.api-list ul {
  padding-left: 15px;
}
.api_list_item {
  font-size: 10px;
}
```

(only tested with Firefox 48 on Linux so far)

**Comment by simonredfern** [comment]
@sebtesobe Please could you implment the above css / make the left panel larger?

**Comment by simonredfern** [comment]
@JamieFarrelly added this comment on OBP-API   It's fairly difficult to read the side menu on the left, at first I thought it was just on mobile that the documentation was a bit dodgy but even on desktop the text is well too small in the side menu. Surely it's worth considering something like slate which is perfect for this type of thing - and mobile friendly.

**Comment by sebtesobe** [comment]
That issue is sorted, right? @simonredfern

**Comment by simonredfern** [comment]
Closing for now. Might want to have button for larger text in left panel.
