### ISSUE TITLE
Create "Messaging" Tag / Cluster of APIs

### ISSUE THREAD

**Issue by ichaib** [OpenBankProject/API-Explorer#13]
"Add Customer Message" & "Get Customer Messages (Current)" to tag "**Messaging**"

https://apiexplorersandbox.openbankproject.com/?ignoredefcat=true&tags=#1_4_0-addCustomerMessage
https://apiexplorersandbox.openbankproject.com/?ignoredefcat=true&tags=#1_4_0-getCustomerMessages

**Comment by sebtesobe** [comment]
The tag is called `Customer`. Please verify and close @ichaib

**Comment by simonredfern** [comment]
Done but with ?tags=Message

Change was done in API resource docs (not API Explorer)

The tag Customer still exists for these endpoints but the first tag is Message so these endpoints are grouped by that.
