### ISSUE TITLE
Create "Card" tag / cluster of APIs

### ISSUE THREAD

**Issue by ichaib** [OpenBankProject/API-Explorer#14]
In API Explorer, Add a tag "Card" with following APIs
Add Cards for a Bank https://apiexplorersandbox.openbankproject.com/?ignoredefcat=true&tags=#2_1_0-addCardsForBank
Get cards for the current user https://apiexplorersandbox.openbankproject.com/?ignoredefcat=true&tags=#1_3_0-getCards
Get cards for the specified bank https://apiexplorersandbox.openbankproject.com/?ignoredefcat=true&tags=#1_3_0-getCardsForBank

**Comment by sebtesobe** [comment]
That exists now, please verify and close @ichaib

**Comment by simonredfern** [comment]
This works OK now: https://apiexplorersandbox.openbankproject.com/?tags=Card
