### ISSUE TITLE
Make left panel nicer looking

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/API-Explorer#22]

**Comment by sebtesobe** [comment]
Check https://apiexplorersandbox.openbankproject.com/ . If there is any more you would like to have changed, please be more specific or ask a graphics designer. :)

**Comment by sebtesobe** [comment]
On a different note: Group `Account` comes after e.g. `APIInfo`. It looks like the sorting algorithm works by ASCII code (or somesuch) and not lexically.
