### ISSUE TITLE
Filter by tags

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/API-Explorer#3]
API Explorer main page should accept comma separated list of tags

e.g.

https://host-apiexplorer.openbankproject.com/?version=2.0.0&psd2=true&tags=tag1,tag2,tag3

then returned list of Resource Docs should be filterd by tag1 AND tag2 AND tag3

**Comment by simonredfern** [comment]
Tags are already in the ResourceDoc model - we just need to get tags out of the query string, split them and use them to filter the list around here: (in APIExplorer.scala)

```
val filteredResources3 : List[ResourceDoc] = showOBWG match {
  case Some(true) => filteredResources2.filter(x => x.isOBWG == true)
  case Some(false) => filteredResources2.filter(x => x.isOBWG == false)
  case _ => filteredResources2
}

val resources = filteredResources3 
```

**Comment by simonredfern** [comment]
Let's call the parameter and_tags i.e. and_tags=tag1,tag2,tag3

**Comment by ghost** [comment]
Example:
manually add into a url for instance next parameter &tags=Banks,Accounts
To remove the parameter from the url just use any existing filter. For instance PSD2, UK...
