### ISSUE TITLE
If Error response, it should wrap, not be on one long line

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/API-Explorer#6]
The error response should wrap not be one line

See image:

<img width="735" alt="make_response_wrap" src="https://cloud.githubusercontent.com/assets/485218/16769197/5e7de37e-4850-11e6-999c-8c6b509757b4.png">

**Comment by somanole** [comment]
Created pull request #7

**Comment by somanole** [comment]
Closed by pull request #7
